// AngularCarlendar_faster/src/app/calendar-cell/calendar-cell.component.ts
import { Component, Input, OnInit, ChangeDetectorRef, ChangeDetectionStrategy } from '@angular/core';
import { Subject } from 'rxjs/Subject';

interface Istatus {
  isSearching: boolean,
  searchResults: {
    options: any
  }
}

@Component({
  selector: 'calendar-cell',
  templateUrl: './calendar-cell.component.html',
  styleUrls: ['./calendar-cell.component.css'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class CalendarCellComponent implements OnInit {

  @Input() hour: number;
  @Input('search') search$: Subject<any>;

  status: Istatus = {
    isSearching: false,
    searchResults: {
      options: null
    }
  };

  private isReady: boolean = false;


  constructor(private cb: ChangeDetectorRef) {
  }

  ngOnInit() {
    this.search$.subscribe(() => {
      this.cellClicked();
    });
  }

  cellClicked(isClick: boolean = false): void {
    this.status.searchResults.options = null;
    this.status.isSearching = true;
    this.cb.markForCheck();
    // simulate AJAX request
    setTimeout(() => {
      this.status.isSearching = false;
      this.status.searchResults = {
        options: Math.floor(Math.random() * 5)
      };
      this.cb.markForCheck();
    }, 0);
  }

  showSpinner() {
    return this.status.isSearching;
  }
  showHour() {
    return !this.status.isSearching && this.status.searchResults.options === null;
  }
  showSearchResults() {
    return this.status.searchResults.options !== null;
  }

}

<div
  [class.goodresults]="status.searchResults.options > 3"
  [class.weakresults]="status.searchResults.options >= 1 && status.searchResults.options <= 3"
  [class.badresults]="status.searchResults.options == 0"
  [class.searching]="status.isSearching"
  >
  <div *ngIf="showSpinner()">
    ...
  </div>
  <div *ngIf="showHour()" class="time">
    {{hour}}:00
  </div>
  <div *ngIf="showSearchResults()" (click)="cellClicked(true)">
    <div>{{status.searchResults.options}}</div>
    <div class="result-label">results</div>
  </div>
</div>

// VueCalendar/src/components/CalendarCell.vue
<template>
  <div
    :class="{
      goodresults: status.searchResults.options > 3,
      weakresults: status.searchResults.options >= 1 && status.searchResults.options <= 3,
      badresults: status.searchResults.options == 0,
      searching: status.isSearching
    }"
    >
    <div v-if="showSpinner()">
      ...
    </div>
    <div v-if="showHour()" class="time">
      {{hour}}:00
    </div>
    <div v-if="showSearchResults()" @click="cellClicked()">
      <div>{{status.searchResults.options}}</div>
      <div class="result-label">results</div>
    </div>
  </div>
</template>

<script>
  export default {
    name: 'calendarCell',
    data() {
      return {
        status: {
          isSearching: false,
          searchResults: {
            options: null
          }
        }
      }
    },
    props: ['hour', 'search'],
    mounted() {
      this.search.subscribe(() => {
        this.cellClicked();
      })
    },
    methods: {
      cellClicked() {
        this.status.searchResults.options = null;
        this.status.isSearching = true;
        // simulate AJAX request
        setTimeout(() => {
          this.status.isSearching = false;
          this.status.searchResults = {
            options: Math.floor(Math.random() * 5)
          };
        }, 0);
      },
      showSpinner() {
        return this.status.isSearching;
      },
      showHour() {
        return !this.status.isSearching && this.status.searchResults.options === null;
      },
      showSearchResults() {
        return this.status.searchResults.options !== null;
      }
    },
  }
</script>

<style>
  .searching {
  color: blue;
  font-size: 10px;
  padding-top: 6px;
}
.goodresults {
  color: #090;
  background: #efffef;
}
.result-label {
  font-size: 8px;
}
.weakresults {
  color: orange;
  background: #ffffef;
}
.badresults {
  color: red;
  background: #ffefef;
}
</style>
